services:
  - type: web
    name: cannabis-lab-api
    env: python
      build:
  command: |
    bash install_chrome.sh
    pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/credentials.json
    secretFiles:
      - source: credentials.json
        mountPath: /etc/secrets/credentials.json
