services:
  - type: web
    name: cannabis-lab-api
    env: python
    buildCommand: |
      apt-get update && apt-get install -y wget gnupg2
      ./install_chrome.sh
      pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/credentials.json
    secretFiles:
      - source: credentials.json
        mountPath: /etc/secrets/credentials.json
